const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const projectRoot = path.resolve(__dirname, '..')
const html = fs.readFileSync(path.join(projectRoot, 'public/index.html'), 'utf8')
const app = fs.readFileSync(path.join(projectRoot, 'public/app.js'), 'utf8')
const styles = fs.readFileSync(path.join(projectRoot, 'public/styles.css'), 'utf8')

test('wires snap, continuous zoom and original-page controls without a background grid', () => {
  for (const controlId of ['grid-size', 'view-scale']) {
    assert.match(html, new RegExp(`id="${controlId}"`))
  }
  assert.doesNotMatch(html, /id="workspace-height-scale"/)
  assert.doesNotMatch(html, /id="grid-toggle"/)
  assert.doesNotMatch(app, /workspaceHeightScale|renderPageBreaks|paginatePages/)
  assert.doesNotMatch(styles, /grid-enabled|icat-export-page-break/)
  assert.match(html, /id="fit-width"/)
  assert.match(html, /id="resolve-overlaps"/)
  assert.match(html, /src="\/history-model\.js"/)
  assert.match(html, /src="\/segmentation-model\.js"/)
  assert.match(html, /id="view-scale" type="range" min="25" max="250"/)
  assert.match(app, /setViewScale\(Number\(elements\.viewScale\.value\)\)/)
  assert.match(app, /fitDocumentWidth/)
  assert.match(app, /resolveSegmentOverlaps/)
  assert.match(app, /getSegmentHorizontalGeometry/)
  assert.match(app, /!sourceElement\.closest\("td, th"\)/)
  assert.match(app, /const pages = state\.pages\.map/)
  assert.match(app, /pageIndex: segment\.pageIndex/)
  assert.match(app, /screenDeltaToDocument/)
  assert.match(app, /event\.ctrlKey \|\| event\.metaKey/)
  assert.match(app, /handleWorkspaceZoom/)
  assert.match(app, /beginMarqueeSelection/)
  assert.match(app, /ICATSegmentation\.collectTextCandidates/)
  assert.match(app, /hideCandidateSource\(candidate\)/)
  assert.match(app, /selectedIds: new Set\(\)/)
  assert.match(app, /clampGroupDelta/)
  assert.match(app, /document\.addEventListener\("keydown", handleUndoShortcut\)/)
  assert.match(app, /function undoLastAction\(\)/)
  assert.match(app, /function restoreHistorySnapshot\(snapshot\)/)
  assert.match(app, /HISTORY_LIMIT = 100/)
  assert.match(app, /origins\.length > 1 \? "групповое перемещение" : "перемещение сегмента"/)
  assert.match(app, /commitHistory\(before, "изменение размера сегмента"/)
  assert.match(app, /commitHistory\(before, "разнесение наложений"/)
  assert.match(html, /Cmd\/Ctrl \+ Z/)
  assert.match(html, /id="selection-count"/)
  assert.match(html, /Cmd\/Ctrl \+ колесо/)
})
