const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const projectRoot = path.resolve(__dirname, '..')
const html = fs.readFileSync(path.join(projectRoot, 'public/index.html'), 'utf8')
const app = fs.readFileSync(path.join(projectRoot, 'public/app.js'), 'utf8')
const styles = fs.readFileSync(path.join(projectRoot, 'public/styles.css'), 'utf8')

test('wires page-only grid, visual page insertion, parking and continuous zoom', () => {
  for (const controlId of ['grid-size', 'view-scale']) {
    assert.match(html, new RegExp(`id="${controlId}"`))
  }
  assert.doesNotMatch(html, /id="workspace-height-scale"/)
  assert.doesNotMatch(html, /id="grid-toggle"/)
  assert.doesNotMatch(app, /workspaceHeightScale|renderPageBreaks|paginatePages/)
  assert.doesNotMatch(styles, /grid-enabled|icat-export-page-break/)
  assert.match(styles, /--grid-size: 4px/)
  assert.match(styles, /#docx-host section\.docx/)
  assert.match(styles, /var\(--grid-size\)/)
  assert.match(html, /id="fit-width"/)
  assert.match(html, /id="upload-button"/)
  assert.match(html, /id="resolve-overlaps"/)
  assert.match(html, /src="\/history-model\.js"/)
  assert.match(html, /src="\/segmentation-model\.js"/)
  assert.match(html, /id="view-scale" type="range" min="25" max="250"/)
  assert.match(app, /setViewScale\(Number\(elements\.viewScale\.value\)\)/)
  assert.match(app, /fitDocumentWidth/)
  assert.match(app, /resolveSegmentOverlaps/)
  assert.match(app, /getSegmentHorizontalGeometry/)
  assert.match(app, /getPhysicalPageSize/)
  assert.match(app, /getFlowPageCount/)
  assert.match(app, /getFlowPagePlacement/)
  assert.match(app, /layoutSequentialFlowBoxes/)
  assert.match(app, /icat-flow-page/)
  assert.match(app, /isCandidateInNormalFlow/)
  assert.doesNotMatch(app, /scrollHeight.*slice|icat-derived-page|getPageSlice/)
  assert.match(app, /renderPageInsertControls/)
  assert.match(app, /insertBlankPage/)
  assert.match(app, /removeEmptyPage/)
  assert.match(app, /undoRemovedPage/)
  assert.match(app, /ICATLayout\.isPageEmpty/)
  assert.match(app, /remapPageIndexAfterRemoval/)
  assert.match(app, /undoInsertedPage/)
  assert.match(app, /commitHistory\(before, "добавление страницы"/)
  assert.match(app, /createParkingArea/)
  assert.match(app, /createEditorLayout/)
  assert.match(app, /setParkingSurfaceWidth/)
  assert.match(app, /observeParkingResize/)
  assert.match(app, /new ResizeObserver/)
  assert.match(app, /measureDropSurfaces/)
  assert.match(app, /findDropSurface/)
  assert.match(app, /requestAnimationFrame\(flushMove\)/)
  assert.match(app, /window\.addEventListener\("pointermove", move\)/)
  const dropLookup = app.match(/function findDropSurface[\s\S]*?\n}/)?.[0] || ''
  assert.doesNotMatch(dropLookup, /getBoundingClientRect/)
  assert.match(app, /ICATLayout\.isDocumentSegment/)
  assert.match(app, /segment\.pageIndex = null/)
  assert.match(app, /state\.parkingOverlay\.style\.height/)
  assert.match(styles, /\.icat-editor-layout[\s\S]*grid-template-columns: max-content max-content/)
  assert.match(styles, /\.icat-parking[\s\S]*position: sticky/)
  assert.match(styles, /\.icat-parking[\s\S]*resize: both/)
  assert.match(styles, /\[hidden\][\s\S]*display: none !important/)
  assert.match(html, /буфер справа от листов/)
  assert.match(app, /!sourceElement\.closest\("td, th"\)/)
  assert.match(app, /const pages = state\.pages\.map/)
  assert.match(app, /pageIndex: segment\.pageIndex/)
  assert.match(app, /screenDeltaToDocument/)
  assert.match(app, /captureZoomAnchor/)
  assert.match(app, /getZoomScrollAdjustment/)
  assert.match(app, /event\.ctrlKey \|\| event\.metaKey/)
  assert.match(app, /handleWorkspaceZoom/)
  assert.match(app, /beginMarqueeSelection/)
  assert.match(app, /ICATSegmentation\.collectTextCandidates/)
  assert.match(app, /hideCandidateSource\(candidate\)/)
  assert.match(app, /selectedIds: new Set\(\)/)
  assert.match(app, /getSegmentActionTargets/)
  assert.match(app, /runEditorAction/)
  assert.match(html, /id="editor-toolbar"/)
  assert.match(html, /id="editor-font-size"/)
  assert.match(html, /data-editor-action="insert-tab"/)
  assert.match(app, /runSelectedEditorAction\("font-size"/)
  assert.match(app, /insertEditorTab/)
  assert.doesNotMatch(app, /const formattingActions =/)
  assert.match(app, /document\.execCommand\(action, false\)/)
  assert.match(app, /"align-left": "left"/)
  assert.match(app, /"align-center": "center"/)
  assert.match(app, /"align-right": "right"/)
  assert.match(app, /изменение жирности текста/)
  assert.match(app, /изменение курсива текста/)
  assert.match(app, /Перемещенные внутрь блока сегменты не будут учавствовать в сборке финального документа/)
  assert.doesNotMatch(styles, /↘ изменить размер/)
  assert.match(app, /Вернуть в исходное положение в документе/)
  assert.doesNotMatch(app, /"restore-page"|"previous-page"|"next-page"/)
  assert.match(app, /clampGroupDelta/)
  assert.match(app, /handleDocumentPointerDown/)
  assert.match(app, /handleFocusShortcut/)
  assert.match(app, /event\.key !== "Escape"/)
  assert.match(app, /clearSegmentFocus/)
  assert.match(app, /elements\.uploadButton\.hidden = isLoading \|\| state\.pages\.length > 0/)
  assert.match(app, /document\.addEventListener\("keydown", handleUndoShortcut\)/)
  assert.match(app, /function undoLastAction\(\)/)
  assert.match(app, /function restoreHistorySnapshot\(snapshot\)/)
  assert.match(app, /HISTORY_LIMIT = 100/)
  assert.match(app, /origins\.length > 1 \? "групповое перемещение" : "перемещение сегмента"/)
  assert.match(app, /commitHistory\(before, "изменение размера сегмента"/)
  assert.match(app, /refreshDragAfterScroll/)
  assert.match(app, /dropSurfaces = measureDropSurfaces\(\)/)
  assert.match(app, /window\.addEventListener\("scroll", refreshDragAfterScroll, true\)/)
  assert.match(app, /elements\.workspace\.addEventListener\("scroll", refreshDragAfterScroll/)
  assert.match(app, /commitHistory\(before, "разнесение наложений"/)
  assert.match(html, /Cmd\/Ctrl \+ Z/)
  assert.match(html, /id="selection-count"/)
  assert.match(html, /id="parked-count"/)
  assert.match(html, /Вне документа:/)
  assert.match(html, /Cmd\/Ctrl \+ колесо/)
})
